jobs:
  test:
    container: ghcr.io/qmk/qmk_cli
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - name: Collect Workflow Telemetry
      uses: Nfsaavedra/workflow-telemetry-action@raw_data
      with:
        save_raw_stats: true
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Install dependencies
      run: pip3 install -r requirements-dev.txt
    - name: Run tests
      run: qmk test-c
name: Unit Tests
'on':
- workflow_dispatch
permissions: write-all
